"""Original procedural RGB565 assets; no third-party image dependencies."""
import argparse
import pathlib
import struct
import zlib


def opaque(shape, x, y):
    dx, dy = abs(2*x-7), abs(2*y-7)
    r = dx*dx+dy*dy
    return (r <= 49, dx+dy <= 8, dx <= 1 or (dx <= 3 and dy <= 3),
            dx <= 1 or dy <= 1, dx <= 1 or dy <= 1 or dx == dy,
            18 <= r <= 49)[shape]


def aircraft(atlas, color, downward=False):
    for y in range(16):
        for x in range(16):
            yy = 15-y if downward else y
            dx = abs(2*x-15)
            body = dx <= 3 and 2 <= yy <= 12
            wing = 5 <= yy <= 12 and dx <= (yy-4)*2
            engine = 13 <= yy <= 15 and dx <= 3
            pixel = (0xffff if body else 0x0430 if wing and yy >= 11 else
                     color if wing else 0xfc80 if engine else 0xf81f)
            atlas += struct.pack('<H', pixel)


def build(out):
    out = pathlib.Path(out)
    out.mkdir(parents=True, exist_ok=True)
    bg = bytearray()
    for y in range(540):
        for x in range(960):
            color = 0
            if y >= 72:
                # Subdued space arena: distant stars, inset rails and circuit grid.
                edge = min(x, 959-x, y-72, 539-y)
                color = (1 << 11) | ((3 + y // 90) << 5) | (7 + y // 135)
                if x % 60 == 0 or (y-72) % 60 == 0:
                    color = 0x1107
                if x % 120 == 0 and (y-72) % 120 == 0:
                    color = 0x29ad
                if ((x*73 + y*151) ^ (x*y*3)) % 4093 < 3:
                    color = 0x4a71
                if edge in (8, 9):
                    color = 0x1a2c
                if 12 <= edge <= 14 and (x//24+y//24) % 3 == 0:
                    color = 0x21af
            bg += struct.pack("<H", color)
    atlas = bytearray()
    for shape, color in enumerate((0x07ff, 0xfc80, 0xb81f, 0x07e0, 0xffe0, 0xf800)):
        for y in range(8):
            for x in range(8):
                r = (2*x-7)**2 + (2*y-7)**2
                pixel = 0xf81f if not opaque(shape,x,y) else 0xffff if r < 10 else 0x4208 if r >= 34 else color
                atlas += struct.pack("<H", pixel)
    aircraft(atlas,0x07ff)
    for y in range(12):
        for x in range(12):
            d = abs(2*x-11) + abs(2*y-11)
            atlas += struct.pack("<H", (max(0, 22-d)*2) << 5)
    for color in (0xfc80,0xb81f,0x07e0):
        aircraft(atlas,color,downward=True)
    (out / "background.rgb565").write_bytes(bg)
    (out / "atlas.rgb565").write_bytes(atlas)
    (out / "manifest.csv").write_text("101,background.rgb565\n102,atlas.rgb565\n", encoding="ascii")
    (out / "bullet_asset_catalog.h").write_text(
        "#ifndef EFINIX_BULLET_ASSET_CATALOG_H\n#define EFINIX_BULLET_ASSET_CATALOG_H\n"
        "/* Generated by tools/build_bullet_assets.py. */\n"
        f"#define BULLET_BACKGROUND_CRC 0x{zlib.crc32(bg):08x}u\n"
        f"#define BULLET_ATLAS_CRC 0x{zlib.crc32(atlas):08x}u\n#endif\n", encoding="ascii")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="sw/efinix_gpu/assets/bullet")
    build(parser.parse_args().out)
