param(
 [string]$InputPng=(Join-Path (Split-Path $PSScriptRoot -Parent) 'sw/efinix_gpu/assets/hud/competition_logo_source.png'),
 [string]$Out=(Join-Path (Split-Path $PSScriptRoot -Parent) 'sw/efinix_gpu/assets/hud')
)
# Deterministic asset import, not generated/recreated artwork. Uses Windows GDI+.
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Drawing
$source=[Drawing.Image]::FromFile((Resolve-Path -LiteralPath $InputPng).Path)
$bitmap=New-Object Drawing.Bitmap 200,70
$graphics=[Drawing.Graphics]::FromImage($bitmap)
$attributes=New-Object Drawing.Imaging.ImageAttributes
try {
 $graphics.Clear([Drawing.Color]::White)
 $graphics.InterpolationMode=[Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
 $graphics.PixelOffsetMode=[Drawing.Drawing2D.PixelOffsetMode]::HighQuality
 $attributes.SetWrapMode([Drawing.Drawing2D.WrapMode]::TileFlipXY)
 $scale=[Math]::Min(200.0/$source.Width,70.0/$source.Height)
 $width=[int][Math]::Round($source.Width*$scale)
 $height=[int][Math]::Round($source.Height*$scale)
 $rectangle=New-Object Drawing.Rectangle ([int]((200-$width)/2)),([int]((70-$height)/2)),$width,$height
 $graphics.DrawImage($source,$rectangle,0,0,$source.Width,$source.Height,[Drawing.GraphicsUnit]::Pixel,$attributes)
 $data=New-Object byte[] 28000
 for($y=0;$y -lt 70;$y++) {for($x=0;$x -lt 200;$x++) {
  $pixel=$bitmap.GetPixel($x,$y)
  # Color channel properties are Byte. PowerShell preserves that width across
  # shifts, silently dropping high bits unless promoted before packing.
  $word=(([int]$pixel.R -shr 3) -shl 11) -bor (([int]$pixel.G -shr 2) -shl 5) -bor ([int]$pixel.B -shr 3)
  $offset=2*($y*200+$x)
  $data[$offset]=[byte]($word -band 255);$data[$offset+1]=[byte]($word -shr 8)
 }}
 [uint32]$crc=4294967295
 foreach($value in $data) {
  $crc=$crc -bxor $value
  for($bit=0;$bit -lt 8;$bit++) {
   if($crc -band 1) {$crc=($crc -shr 1) -bxor [uint32]3988292384} else {$crc=$crc -shr 1}
  }
 }
 $crc=$crc -bxor [uint32]4294967295
 New-Item -ItemType Directory -Force -Path $Out | Out-Null
 [IO.File]::WriteAllBytes((Join-Path $Out 'competition_logo.rgb565'),$data)
 $bitmap.Save((Join-Path $Out 'competition_logo.preview.png'),[Drawing.Imaging.ImageFormat]::Png)
 $hex=$crc.ToString('x8')
 [IO.File]::WriteAllText((Join-Path $Out 'hud_logo_catalog.h'),
  "#ifndef EFINIX_HUD_LOGO_CATALOG_H`n#define EFINIX_HUD_LOGO_CATALOG_H`n/* Generated by tools/build_hud_logo.ps1; pixels stay on the PC, not in BSS. */`n#define HUD_LOGO_CRC32 0x${hex}u`n#endif`n",[Text.Encoding]::ASCII)
 $metadata=@{source_width=$source.Width;source_height=$source.Height;width=200;height=70;stride_bytes=400;bytes=28000;
  source_sha256=(Get-FileHash -LiteralPath $InputPng -Algorithm SHA256).Hash.ToLowerInvariant();crc32=$hex;
  format='RGB565_LE';license='User-supplied competition mark; not CC0'}
 [IO.File]::WriteAllText((Join-Path $Out 'logo_source.json'),($metadata|ConvertTo-Json)+"`n",(New-Object Text.UTF8Encoding $false))
 Write-Output "PASS imported original $($source.Width)x$($source.Height) -> 200x70, 28000B RGB565_LE, CRC=$hex"
} finally {$attributes.Dispose();$graphics.Dispose();$bitmap.Dispose();$source.Dispose()}
