"""Convert CC0 Kenney PNGs into the V2 RGB565 network resource package."""

import pathlib
import struct
import zlib

from PIL import Image, ImageDraw


WIDTH, HEIGHT = 960, 540
SPRITE_SIZE = (64, 80)
COLOR_KEY = 0xF81F
ASSETS = (
    (1, "scene.rgb565", 0x02400000, "SCENE"),
    (2, "flower.rgb565", 0x02600000, "FLOWER"),
    (3, "zombie_walk1.rgb565", 0x02610000, "ZOMBIE_WALK1"),
    (4, "zombie_walk2.rgb565", 0x02620000, "ZOMBIE_WALK2"),
)


def rgb565(image):
    data = bytearray(image.width * image.height * 2)
    for index, (r, g, b, a) in enumerate(image.convert("RGBA").getdata()):
        value = COLOR_KEY if a < 128 else ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        struct.pack_into("<H", data, index * 2, value)
    return bytes(data)


def build(source, out):
    source, out = pathlib.Path(source), pathlib.Path(out)
    out.mkdir(parents=True, exist_ok=True)
    tile = Image.open(source / "kenney_grass_tile.png").convert("RGBA")
    scene = Image.new("RGBA", (WIDTH, HEIGHT))
    for y in range(0, HEIGHT, tile.height):
        for x in range(0, WIDTH, tile.width):
            scene.alpha_composite(tile, (x, y))
    lane_shade = Image.new("RGBA", (WIDTH, HEIGHT))
    shade_draw = ImageDraw.Draw(lane_shade)
    for row in range(1, 5, 2):
        y = 60 + row * 96
        shade_draw.rectangle((64, y, 927, y + 95), fill=(0, 0, 0, 32))
    scene = Image.alpha_composite(scene, lane_shade)
    draw = ImageDraw.Draw(scene, "RGBA")
    draw.rectangle((0, 0, WIDTH - 1, 59), fill=(80, 50, 25, 255))
    draw.rectangle((0, 60, 63, HEIGHT - 1), fill=(92, 66, 40, 255))
    draw.rectangle((928, 60, WIDTH - 1, HEIGHT - 1), fill=(87, 62, 43, 255))
    for row in range(5):
        y = 60 + row * 96
        draw.line((64, y, 927, y), fill=(219, 241, 166, 130), width=2)
    for col in range(10):
        x = 64 + col * 96
        draw.line((x, 60, x, HEIGHT - 1), fill=(42, 125, 63, 95), width=2)
    for slot in range(5):
        x = 14 + slot * 86
        draw.rounded_rectangle((x, 8, x + 76, 52), radius=7,
                               fill=(178, 145, 81, 255), outline=(242, 222, 150, 255), width=2)

    sprites = [Image.open(source / name).convert("RGBA").resize(SPRITE_SIZE, Image.Resampling.LANCZOS)
               for name in ("kenney_flower.png", "kenney_zombie_walk1.png", "kenney_zombie_walk2.png")]
    images = [scene, *sprites]
    manifest = []
    header = ["#ifndef EFINIX_ASSET_CATALOG_H", "#define EFINIX_ASSET_CATALOG_H",
              "/* Generated by tools/build_v2_assets.py; RGB565 little-endian. */",
              f"#define ASSET_COLOR_KEY 0x{COLOR_KEY:04x}u",
              "#define ASSET_SCENE_WIDTH 960u", "#define ASSET_SCENE_HEIGHT 540u",
              "#define ASSET_SPRITE_WIDTH 64u", "#define ASSET_SPRITE_HEIGHT 80u"]
    for (asset_id, filename, address, symbol), image in zip(ASSETS, images):
        data = rgb565(image)
        (out / filename).write_bytes(data)
        manifest.append(f"{asset_id},{filename}")
        header += [f"#define ASSET_ID_{symbol} {asset_id}u",
                   f"#define ASSET_{symbol}_ADDR 0x{address:08x}u",
                   f"#define ASSET_{symbol}_BYTES {len(data)}u",
                   f"#define ASSET_{symbol}_CRC 0x{zlib.crc32(data):08x}u"]
    (out / "manifest.csv").write_text("\n".join(manifest) + "\n", encoding="ascii")
    (out / "asset_catalog.h").write_text("\n".join(header + ["#endif", ""]), encoding="ascii")
    preview = scene.copy()
    for row in range(5):
        preview.alpha_composite(sprites[0], (80 + (row % 3) * 96, 68 + row * 96))
        preview.alpha_composite(sprites[1 + (row % 2)], (832 - row * 50, 68 + row * 96))
    preview.convert("RGB").save(out / "preview.png")


if __name__ == "__main__":
    root = pathlib.Path(__file__).resolve().parents[1]
    build(root / "sw/efinix_gpu/assets/source", root / "sw/efinix_gpu/assets/v2")
