"""V3 package: original procedural R7 art, unchanged ASST IDs and GPU layout."""
import argparse
import hashlib
import importlib.util
import json
import pathlib
import tempfile
import zlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_EPOCH = 0x00030001


def build(out, epoch=DEFAULT_EPOCH):
    if not isinstance(epoch, int) or isinstance(epoch, bool) or not 0 < epoch <= 0xffffffff:
        raise ValueError("resource epoch must be a nonzero u32")
    out = pathlib.Path(out)
    out.mkdir(parents=True, exist_ok=True)
    source = ROOT / "tools/build_bullet_assets.py"
    spec = importlib.util.spec_from_file_location("r7_asset_builder", source)
    builder = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(builder)
    assets = []
    with tempfile.TemporaryDirectory() as temporary:
        builder.build(temporary)
        for identifier, name, width, height, stride, address in (
            (101, "background.rgb565", 960, 540, 1920, 0x02900000),
            (102, "atlas.rgb565", None, None, None, 0x02a00000),
        ):
            data = (pathlib.Path(temporary) / name).read_bytes()
            if address + len(data) > (0x02a00000 if identifier == 101 else 0x02b00000):
                raise ValueError("resource overlaps the next reserved DDR region")
            (out / name).write_bytes(data)
            assets.append(dict(id=identifier, file=name, width=width, height=height,
                               stride_bytes=stride, format="RGB565_LE", bytes=len(data),
                               ddr_address=address, crc32=f"{zlib.crc32(data):08x}",
                               sha256=hashlib.sha256(data).hexdigest(), license="CC0-1.0"))
    atlas_bytes = assets[1]["bytes"]
    if atlas_bytes > 4096:
        raise ValueError("V3 initial atlas must fit the existing 4 KiB texture cache")
    manifest = dict(schema_version=1, resource_epoch=epoch, scene="V3 interactive survival",
                    format="RGB565_LE", color_key=0xf81f, atlas_bytes=atlas_bytes,
                    texture_cache_limit=4096, invalidate_both_buffers_before_load=True,
                    require_complete_crc_before_visible=True,
                    baseline_art="R7 procedural art; identical bytes, separate game input",
                    source="tools/build_bullet_assets.py", assets=assets,
                    atlas_layout=[dict(name="bullet_" + str(i), offset=i*128, width=8,
                                       height=8, stride_bytes=16) for i in range(6)] +
                    [dict(name="player", offset=768, width=16, height=16, stride_bytes=32),
                     dict(name="glow", offset=1280, width=12, height=12, stride_bytes=24)] +
                    [dict(name="enemy_" + str(i), offset=1568+i*512, width=16,
                          height=16, stride_bytes=32) for i in range(3)])
    (out / "resource_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (out / "manifest.csv").write_text("101,background.rgb565\n102,atlas.rgb565\n", encoding="ascii")
    (out / "LICENSES.md").write_text(
        "# V3 interactive resource sources and licenses\n\n"
        "These new package files contain project-original procedural art generated by "
        "`tools/build_bullet_assets.py`: star/circuit arena, six bullet shapes, "
        "player fighter, glow and three enemy fighters. No third-party artwork or "
        "game source is included. The generated resource files in this directory "
        "are dedicated to the public domain under CC0-1.0.\n\n"
        "Source: https://github.com/fortitude24102-lang/competition/blob/main/tools/build_bullet_assets.py\n\n"
        "License: https://creativecommons.org/publicdomain/zero/1.0/legalcode\n\n"
        "100KBBH is a gameplay reference only; no upstream assets are redistributed. "
        "The frozen R7 package is not overwritten by this generator.\n", encoding="utf-8")
    return manifest


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="sw/efinix_gpu/assets/interactive")
    parser.add_argument("--epoch", type=lambda value: int(value, 0), default=DEFAULT_EPOCH)
    args = parser.parse_args()
    build(args.out, args.epoch)
