#ifndef EFINIX_BULLET_ASSET_CATALOG_H
#define EFINIX_BULLET_ASSET_CATALOG_H
/* Generated by tools/build_bullet_assets.py. */
#define BULLET_BACKGROUND_CRC 0x059c12b3u
#define BULLET_ATLAS_CRC 0x1dc74ff4u
#endif
